"""Add xml file name to documents

Revision ID: 2c444fe387d4
Revises: 54eb00c51074
Create Date: 2025-03-07 13:29:44.536125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c444fe387d4'
down_revision: Union[str, None] = '54eb00c51074'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('xmlFileName', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'xmlFileName')
    # ### end Alembic commands ###
